[pytest]
# Thêm thư mục gốc vào Python path để import page/core/utils hoạt động
pythonpath = .

# Hiển thị log ra console khi chạy test
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)-8s | %(name)s | %(message)s
log_cli_date_format = %H:%M:%S

# Chạy với verbose output, tạo HTML report
addopts = -v --tb=short --html=reports/report.html --self-contained-html

# Đánh dấu test markers (tránh warning)
markers =
    tc01: Dynamic Loading
    tc02: File Upload
    tc03: JS Alerts
    tc04: iFrame
    tc05: Multiple Windows
    tc06: File Download
